spring:
  main:
    web-application-type: none
  profiles:
    active: production
  datasource:
    url: jdbc:oracle:thin:@192.168.6.220:1521:esb
    username: esb
    password: esb

server:
  port: 8089

logging:
  config: config/log4j2.xml

mq:
  host: localhost
  port: 1414
  queue-manager: QM1
  queue: Q1
  channel: CH1
  receive-timeout: 2000

jms-listener:
  concurrency: 5-10

isdn-analyzer:
  initial-delay: 30000
  fixed-delay: 30000

log-insert:
  batch-size: 500
  retry-time: 3
  retry-sleep: 1000
  pool:
    core-size: 5

log-listening:
  pool:
    min-size: 5
    max-size: 10
    queue-capacity: 200000

async-monitor:
  initial-delay: 30000
  fixed-delay: 30000